# Save as .codeclimate.yml (note leading .) in project root directory
engines:
  fixme:
    enabled: true
  pep8:
    enabled: true
    max-line-length: 140
  radon:
    enabled: true
ratings:
  paths:
  - "**.py"
exclude_paths:
  - "ci/**/*"
  - "tests/**/*"
  - "docs/**/*"
  - "setup.py"