language: python

python:
  - '2.7'
  - '3.3'
  - '3.4'
  - '3.5'

sudo: false
  
addons:
  apt:
    packages:
    - python-numpy
    - gfortran

env:

  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so

  matrix:
    - TOXENV=2.7,extension-coveralls,coveralls,codecov
      WITH_COVERAGE=yes
      PY_CCOV=-coverage
      TESTSCRIPT=py.test --cov --cov-report=term-missing


    - TOXENV=2.7-nocover
      TESTSCRIPT=py.test

    - TOXENV=3.3,extension-coveralls,coveralls,codecov
      WITH_COVERAGE=yes
      PY_CCOV=-coverage
      TESTSCRIPT=py.test --cov --cov-report=term-missing


    - TOXENV=3.3-nocover
      TESTSCRIPT=py.test

    - TOXENV=3.4,extension-coveralls,coveralls,codecov
      WITH_COVERAGE=yes
      PY_CCOV=-coverage
      TESTSCRIPT=py.test --cov --cov-report=term-missing


    - TOXENV=3.4-nocover
      TESTSCRIPT=py.test

    - TOXENV=3.5,extension-coveralls,coveralls,codecov
      WITH_COVERAGE=yes
      PY_CCOV=-coverage
      TESTSCRIPT=py.test --cov --cov-report=term-missing


    - TOXENV=3.5-nocover
      TESTSCRIPT=py.test

    - TOXENV=check
      TESTSCRIPT=python setup.py check --strict --metadata --restructuredtext && check-manifest && flake8 src tests
      INSTALL_EXTRA_DEPS=pip install docutils check-manifest flake8 readme pygments

before_install:
  - python --version
  - uname -a
  - lsb_release -a

install:
  - $INSTALL_EXTRA_DEPS
  - pip install pytest-capturelog coveralls pytest-cov
  - python setup.py clean --all build_ext --force --inplace
  - python setup.py develop

script:
  - $TESTSCRIPT

notifications:
  email:
    on_success: never
    on_failure: always
