image:
- Visual Studio 2019
version: '{branch}-{build}'
build: off
configuration: Release
environment:
  matrix:
    - TESTENV: '2.7-nocover-64'
      INSTALL_LIBPYTHON: libpython
      PYTHON_VERSION: '2.7'
      MINICONDA_HOME: C:\Miniconda-x64
      TESTSCRIPT: 'py.test'
      MINGW_DIR: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin

    - TESTENV: '2.7-nocover-32'
      INSTALL_LIBPYTHON: libpython
      PYTHON_VERSION: '2.7'
      MINICONDA_HOME: C:\Miniconda
      TESTSCRIPT: 'py.test'
      MINGW_DIR: C:\MinGW\bin

    - TESTENV: '3.5-nocover-64'
      PYTHON_VERSION: '3.5'
      MINICONDA_HOME: C:\Miniconda-x64
      TESTSCRIPT: 'py.test'

    - TESTENV: '3.5-nocover-32'
      PYTHON_VERSION: '3.5'
      MINICONDA_HOME: C:\Miniconda
      TESTSCRIPT: 'py.test'

    - TESTENV: '3.6-nocover-64'
      INSTALL_LIBPYTHON: libpython
      PYTHON_VERSION: '3.6'
      MINICONDA_HOME: C:\Miniconda-x64
      TESTSCRIPT: 'py.test'

    - TESTENV: '3.6-nocover-32'
      INSTALL_LIBPYTHON: libpython
      PYTHON_VERSION: '3.6'
      MINICONDA_HOME: C:\Miniconda
      TESTSCRIPT: 'py.test'

    - TESTENV: '3.7-nocover-64'
      INSTALL_LIBPYTHON: libpython
      PYTHON_VERSION: '3.7'
      MINICONDA_HOME: C:\Miniconda-x64
      TESTSCRIPT: 'py.test'

    - TESTENV: '3.7-nocover-32'
      INSTALL_LIBPYTHON: libpython
      PYTHON_VERSION: '3.7'
      MINICONDA_HOME: C:\Miniconda
      TESTSCRIPT: 'py.test'

    - TESTENV: 'check'
      INSTALL_LIBPYTHON: libpython
      PYTHON_VERSION: '2.7'
      MINICONDA_HOME: 'C:\Miniconda'
      TESTSCRIPT: 'python setup.py check --strict --metadata --restructuredtext && check-manifest && flake8 src tests'
      INSTALL_EXTRA_DEPS: 'pip install docutils check-manifest flake8 readme pygments'

init:
  - ps: echo $env:TESTENV
install:
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
          https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
          Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
            throw "There are newer queued builds for this pull request, failing early." }
  - set PATH=%MINGW_DIR%;%PATH%
  - '%MINICONDA_HOME%\Scripts\conda config --set always_yes yes'
  - '%MINICONDA_HOME%\Scripts\conda update -q conda'
  - '%MINICONDA_HOME%\Scripts\conda create -q -p C:\pythontest python=%PYTHON_VERSION% %INSTALL_LIBPYTHON% pytest numpy'
  # remove file which conflicts with installation of package 'readme' on case-insensitive file systems
  - del C:\pythontest\Lib\site-packages\README
  # to stop the unnecessary "Only MS compiler supported with gfortran on win64" error on some configurations (numpy 1.9?)
#  - python ci\fix-compiler-error.py
  - '%MINICONDA_HOME%\Scripts\activate C:\pythontest'
  - where python
  - where pip
  - '%INSTALL_EXTRA_DEPS%'
  - python setup.py clean --all build_ext --inplace --force
  - python setup.py develop
test_script:
  - '%TESTSCRIPT%'

after_test:
  - python setup.py sdist bdist_wheel

deploy_script:
  # if tagged commit, build/upload wheel
  - IF "%APPVEYOR_REPO_TAG%"=="true" IF NOT "%TESTENV%"=="check" (
      pip install twine &&
      python setup.py register &&
      twine upload -u %PYPI_USER% -p %PYPI_PASS% dist/*
    )

artifacts:
  - path: dist\*
matrix:
  allow_failures:
    - PYTHON_VERSION: '3.5'
    - TESTENV: '2.7-nocover-64'
    - TESTENV: '3.5-nocover-64'
    - TESTENV: '3.6-nocover-64'
    - TESTENV: 'check'
### To enable remote debugging uncomment this:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

