version: '{branch}-{build}'
build: off
configuration: Release
environment:
  matrix:
    - PYTHON_VERSION: "2.7"
      CONDAPATH: 'C:\Miniconda'
    - PYTHON_VERSION: "3.5"
      CONDAPATH: 'C:\Miniconda35'
    - PYTHON_VERSION: "3.6"
      CONDAPATH: 'C:\Miniconda36'
    - PYTHON_VERSION: "3.7"
      CONDAPATH: 'C:\Miniconda37'
platform:
  - x86
  - x64

init:
  - ps: echo $env:TESTENV
install:
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
          https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
          Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
            throw "There are newer queued builds for this pull request, failing early." }
  - if "%PLATFORM%" == "x86" set PATH=%CONDPATH%\bin;%CONDAPATH%\Scripts;%PATH%
  - if "%PLATFORM%" == "x64" set PATH=%CONDPATH%-x64\bin;%CONDAPATH%-x64\Scripts;%PATH%
  - conda config --set always_yes yes
  - conda update -q conda
  - conda create -q -p C:\pythontest python=%PYTHON_VERSION% pytest numpy
  - activate C:\pythontest
  - conda install -q -c msys2 m2w64-toolchain
  - python.exe setup.py config_fc
  - python setup.py clean --all build_ext --force --inplace --compiler=mingw32 --fcompiler=gfortran
  - python setup.py develop

test_script:
  - py.test

after_test:
  - python setup.py sdist bdist_wheel

deploy_script:
  # if tagged commit, build/upload wheel
  - IF "%APPVEYOR_REPO_TAG%"=="true" IF NOT "%TESTENV%"=="check" (
      pip install twine &&
      python setup.py register &&
      twine upload -u %PYPI_USER% -p %PYPI_PASS% dist/*
    )

artifacts:
  - path: dist\*
matrix:
  allow_failures:
    - PYTHON_VERSION: '3.5'
    - TESTENV: '2.7-nocover-64'
    - TESTENV: '3.5-nocover-64'
    - TESTENV: '3.6-nocover-64'
    - TESTENV: 'check'
### To enable remote debugging uncomment this:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

