language: python

python:
  - '2.7'
  - '3.3'
  - '3.4'
  - '3.5'

sudo: false

addons:
  apt:
    packages:
    - python-numpy
    - gfortran

env:

  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so

  matrix:
    - TESTENV=extension-coveralls,coveralls,codecov
      TESTSCRIPT=$(py.test --cov --cov-report=term-missing)

    - TESTENV=nocover
      TESTSCRIPT=$(py.test)

    - TESTENV=check
      TESTSCRIPT=$(python setup.py check --strict --metadata --restructuredtext ; check-manifest ; flake8 src tests)
)
      INSTALL_EXTRA_DEPS='pip install docutils check-manifest flake8 readme pygments'

before_install:
  - python --version
  - uname -a
  - lsb_release -a

install:
  - $INSTALL_EXTRA_DEPS
  - pip install pytest-capturelog coveralls pytest-cov
  - python setup.py clean --all build_ext --force --inplace
  - python setup.py develop

script:
  - $TESTSCRIPT

notifications:
  email:
    on_success: never
    on_failure: always

matrix:
  exclude:
    - python: '3.3'
      env: TESTENV=check
    - python: '3.4'
      env: TESTENV=check
    - python: '3.5'
      env: TESTENV=check