# This workflow will install Python dependencies, run tests and lint with a
# variety of Python versions. For more information see:
# https://help.github.com/actions/language-and-framework-guides/
# using-python-with-github-actions

name: unittest with flake8

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    env:
       FC: gfortran

    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install standard and test dependencies, then apexpy
      run: |
        pip install -r requirements.txt
        bash requirements.extra 0
        python setup.py install

    - name: Test docs
      if: contains(matrix.os, "ubuntu") && contains(matrix.python-version, "3.9")
      run: tox -e docs

    - name: Run unit and integration tests
      run: tox -e ${{ matrix.python-version }}

    - name: Publish results to coveralls upon success
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: coveralls --rcfile=setup.cfg --service=github
