# This workflow will install Python dependencies, run tests and lint with a
# variety of Python versions. For more information see:
# https://help.github.com/actions/language-and-framework-guides/
# using-python-with-github-actions

name: pytest on Windows

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: LockHunter
      run: choco install lockhunter

    - name: Set up Python ${{ matrix.python-version }} with Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: test
        python-version: ${{ matrix.python-version }}
        auto-activate-base: false

    - name: Install standard and test dependencies
      shell: bash -l {0}
      run: conda install -q -c msys2 m2w64-toolchain coveralls numpy pytest pytest-cov scipy

    - name: Install on Windows
      shell: bash -l {0}
      run: python setup.py config --compiler=mingw32 --fcompiler=gnu95 install

    - name: Run unit and integration tests
      shell: bash -l {0}
      run: |
           cd ..
           pwd
           dir .
           LockHunter.exe -u apexpy
           mv -f apexpy proj_dir
           dir .
           cd proj_dir
           dir apexpy
           python -m pytest --cov=apexpy

    - name: Publish results to coveralls upon success
      shell: bash -l {0}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
           coverage combine
           coverage report -m
           coveralls --rcfile=setup.cfg --service=github
